backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

locale: 'de'

media_folder: static/img
public_folder: /img

collections:
  - name: "infos"
    label: "Aktuelles"
    format: "json"
    folder: "content/infos"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown", required: false }
  - name: "sidebar"
    label: "Seiten Navigaion"
    format: "json"
    folder: "content/sidebarNav"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Bild", name: "image", widget: "image", required: false}
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
      - { label: "Link Text", name: "linkText", widget: "string", required: false }
      - label: "Link Adresse"
        name: "link"
        widget: "relation"
        collection: "speisekarten"
        search_fields: ["title"]
        value_field: "/menu/{{slug}}"
        display_fields: ["title"]
        required: false
      - { label: "Beschreibung", name: "description", widget: "markdown", required: false}
  - name: "speisekarten"
    label: "Speisekarten"
    format: "json"
    folder: "content/menu"
    create: true
    slug: "menu/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Name der Speisekarte", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
      - { label: "Wochentage einblenden", name: "showWeekDays", widget: "boolean", default: false, required: false}
      - label: "Platzierung"
        name: "placed"
        widget: "select"
        required: false
        options:
          - { label: "", value: "" }
          - { label: "Startseite", value: "Startseite" }
      - { label: "Position", name: "position", widget: "number", required: false }
      - label: "Speisekarte / Textblock"
        name: "contentblock"
        widget: "list"
        add_to_top: true
        collapsed: false
        required: false
        fields: 
          - { label: "Überschrift", name: "title", widget: "string", required: false }
          - label: "Speisen"
            name: "speisen"
            widget: "list"
            add_to_top: true
            collapsed: false
            fields:
              - {label: Gericht, name: food, widget: string }
              - {label: Beilage, name: garnish, widget: string, required: false }
              - {label: Preis, name: price, widget: number, value_type: "float" }
          - { label: "Extra Beschreibung", name: "description", widget: "markdown", required: false }
      - label: "Banner einblenden"
        name: "showBanner"
        widget: "object"
        fields:
          - { label: "Titel", name: "title", widget: "string", required: false }
          - { label: "Beschreibung", name: "description", widget: "string", required: false }
          - { label: "Button Text", name: "buttonText", widget: "string", required: false }
          - { label: "Button link", name: "buttonLink", widget: "string", required: false }
  - name: "important"
    label: "Wichtige Seiten"
    format: "json"
    folder: "content/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "markdown", required: false }
  - name: "openingHours"
    label: "Öffnungszeiten"
    format: "json"
    folder: "content/openingHours"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Wochentage"
        name: "weekdays"
        widget: "list"
        add_to_top: true
        collapsed: false
        fields:
          - {label: "Wochentag", name: "title", required: true}
          - {label: "Geschlossen", name: "closed", widget: "boolean", default: false}
          - {label: "Grund", name: "reason", widget: "string", default: "", required: false}
  - name: "contactinformations"
    label: "Kontaktinformationen"
    format: "json"
    folder: "content/contactinformations"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Telefon", name: "phone", required: false}
      - {label: "Adresse", name: "adress", required: false}
    
